In [ ]:
# Numpy and Pandas Practise

In [11]:
import numpy as np

In [7]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [10]:
l=[1,2,3,4]
l

[1, 2, 3, 4]

In [14]:
python_list=list(range(100))
python_list[:10]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [24]:
import sys
sys.getsizeof(python_list[0])*len(python_list)

2800

In [42]:
numpy_array=np.arange(100)
numpy_array[:5]

array([0, 1, 2, 3, 4])

In [36]:
## help(np) thsi is there to know the documentation 

In [44]:
numpy_array.nbytes

800

In [3]:
l1=[1,2,3,4,5]
l2=[6,7,8,10]
l3=tuple(zip(l1,l2)) # zip is basically the combining element in the form taking one element from l1 and other element from l2 them combining it 
l3

((1, 6), (2, 7), (3, 8), (4, 10))

In [7]:
import time
SIZE=1000000
l1=list(range(SIZE))
l2=list(range(SIZE))

l3=[x+y for x,y in zip(l1,l2)]
l3[:20]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38]

In [13]:
start_time=time.time()
n1=np.arange(SIZE)
n2=np.arange(SIZE)
n3=n1+n2
end_time=time.time()
print('array took :',end_time-start_time)
n1[:4],n2[:3]

array took : 0.01343679428100586


(array([0, 1, 2, 3]), array([0, 1, 2]))

In [15]:
n1=np.arange(10)
n2=np.arange(10)
n3=n1*n2-n1
n3

array([ 0,  0,  2,  6, 12, 20, 30, 42, 56, 72])

In [35]:
rev_q1=np.array(([10,12,9]))
rev_q1.ndim

1

In [39]:
rev=np.array(([12,23,34],[45,56,67]))
rev

array([[12, 23, 34],
       [45, 56, 67]])

In [45]:
rev[0,2]

34

In [47]:
# .size is used for the number of elements

In [49]:
# .itemsize tells the number of bytes occupies by the each element 

In [51]:
# .shape tells the number of columnand number of row in a matrix.


In [63]:
rev.sort(axis=-1)
rev

array([[12, 23, 34],
       [45, 56, 67]])

In [95]:
arr=np.array([[6,7,3],[22,10,2]])

In [103]:
np.sort(arr,axis=None)   # this makes a liner array of all the elements present in any order array

array([ 2,  3,  6,  7, 10, 22])

In [107]:
np.ones((3,4))    # similarly is for np.zeros is make a array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [111]:
np.linspace(10,20,5) # this will put elements in between a and b of equally spaced numbers

array([10. , 12.5, 15. , 17.5, 20. ])

In [113]:
# .flatten() is used to make a linear arr ,.reshape() is used change the dimension of array ,.min(),.max()

In [117]:
rev.sum(axis=0)  # axis =0 this will take the elements in column format 

array([ 57,  79, 101])

In [121]:
rev.sum(axis=1)  # axis =1 will take the elements in row format

array([ 69, 168])

In [123]:
rev


array([[12, 23, 34],
       [45, 56, 67]])

In [125]:
for row in rev:
    print("row-->",row)

row--> [12 23 34]
row--> [45 56 67]


In [138]:
b=np.array([2,3,4,5,6])  # .sqrt() will give us the root of this function ,